# Generated by Django 4.2.1 on 2023-05-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDjango',
        ),
    ]
